from .prompts import (
    ENTITY_EXTRACTION_EXAMPLE_ATHLETICS,
    ENTITY_EXTRACTION_EXAMPLE_MARKETS,
    ENTITY_EXTRACTION_EXAMPLE_STORY,
)
from .prompts.entity_continue_extraction import (
    USER_PROMPT_TEMPLATE as ENTITY_CONTINUE_EXTRACTION_USER_PROMPT,
)
from .prompts.entity_extraction_system import (
    SYSTEM_PROMPT_TEMPLATE as ENTITY_EXTRACTION_SYSTEM_PROMPT,
)
from .prompts.entity_extraction_user import (
    USER_PROMPT_TEMPLATE as ENTITY_EXTRACTION_USER_PROMPT,
)

DEFAULT_TUPLE_DELIMITER = "<|#|>"
DEFAULT_COMPLETION_DELIMITER = "<|COMPLETE|>"

__all__ = [
    "DEFAULT_COMPLETION_DELIMITER",
    "DEFAULT_TUPLE_DELIMITER",
    "ENTITY_CONTINUE_EXTRACTION_USER_PROMPT",
    "ENTITY_EXTRACTION_EXAMPLE_ATHLETICS",
    "ENTITY_EXTRACTION_EXAMPLE_MARKETS",
    "ENTITY_EXTRACTION_EXAMPLE_STORY",
    "ENTITY_EXTRACTION_SYSTEM_PROMPT",
    "ENTITY_EXTRACTION_USER_PROMPT",
]
