# Generated by Django 6.0.3 on 2026-03-20 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_lightrag", "0002_remove_document_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relation",
            name="source_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_relations",
                to="django_lightrag.entity",
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="target_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_relations",
                to="django_lightrag.entity",
            ),
        ),
    ]
