# Generated by Django 6.0.3 on 2026-03-20 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_lightrag", "0003_alter_relation_source_entity_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VectorEmbedding",
        ),
    ]
