# Generated by Django 6.0.3 on 2026-03-20 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_lightrag", "0004_delete_vectorembedding"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CacheEntry",
        ),
    ]
