# Generated by Django 6.0.3 on 2026-03-20 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_lightrag", "0005_delete_cacheentry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProcessingJob",
        ),
    ]
